services:
  dengine-api:
    container_name: dengine-api-${VERSION}
    build: ./api
    env_file: ".env"
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - back
    volumes:
      - api:/var/www/dengine-api-${VERSION}/

volumes:
  api:
    name: ${API_VOLUME}

networks:
  back:
    external: true
    name: ${BACK_NETWORK}
