// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/about.json": {
            "get": {
                "description": "Gives informations about api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "about.json"
                ],
                "summary": "Gives informations about api",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/endpoints.About"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Connection of a user \u003cbr\u003eToken will be set in cookies if the arguments combination is valid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connection of a user",
                "parameters": [
                    {
                        "description": "Email + Password combination of the corresponding user",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.Creds"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.PostLoginResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "put": {
                "description": "Disconnection of the user \u003cbr\u003eThe token in the Cookies will be deleted after this route has been called",
                "tags": [
                    "auth"
                ],
                "summary": "Disconnection of the user",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/auth/oauth": {
            "post": {
                "description": "Connection of a user using an OAuth \u003cbr\u003eToken will be set in cookies if the arguments combination is valid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connection of a user",
                "parameters": [
                    {
                        "description": "Code + Service combination of the corresponding OAuth",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.OauthArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.PostResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Creation and connection of a new user \u003cbr\u003eToken will be set in cookies if the arguments combination is valid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Creation and connection of a new user",
                "parameters": [
                    {
                        "description": "User related informations that will be later needed for the login process",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.PostLoginResponse"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Healthcheck used (mainly by docker) to check if the api is up and ready to respond",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Healthcheck for the api",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user": {
            "get": {
                "description": "Reads the actual user data \u003cbr\u003e\u003cbr\u003e\u003cb\u003e⚠️ The user must be logged in\u003cb\u003e",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Reads the actual user data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.UserReadResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the actual user \u003cbr\u003e\u003cbr\u003e\u003cb\u003e⚠️ The user must be logged in\u003cb\u003e",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Updates the actual user",
                "parameters": [
                    {
                        "description": "New arguments to be set in the user",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/structs.PostLoginResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes the actual user \u003cbr\u003e \u003cb\u003eCareful, there is no turn back or check, once called, this route will delete the user no matter what\u003c/b\u003e \u003cbr\u003e It also deletes all content related to the user \u003cbr\u003e\u003cbr\u003e\u003cb\u003e⚠️ The user must be logged in\u003cb\u003e",
                "tags": [
                    "user"
                ],
                "summary": "Deletes the actual user",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.Creds": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.OauthArgs": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "service_name": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterArgs": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "endpoints.About": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "structs.PostLoginResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "structs.PostResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "user.UpdateArgs": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.UserReadResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
