// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/about.json": {
            "get": {
                "description": "Gives informations about api",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apidata"
                ],
                "summary": "Gives informations about api",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apidata.About"
                        }
                    }
                }
            }
        },
        "/api/CRUDTEMPLATEs": {
            "get": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eReads all CRUDTEMPLATEs data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CRUDTEMPLATEs"
                ],
                "summary": "Reads all CRUDTEMPLATEs data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/CRUDTEMPLATE.DbReadResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eCreates a CRUDTEMPLATE with arguments in body\u003cbr\u003e\u003cbr\u003eWill return the id of created CRUDTEMPLATE",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CRUDTEMPLATEs"
                ],
                "summary": "Creates a CRUDTEMPLATE",
                "parameters": [
                    {
                        "description": "CRUDTEMPLATE related informations that will be later needed for the login process",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CRUDTEMPLATE.CreateCRUDTEMPLATEsArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/structs.PostResponse"
                        }
                    }
                }
            }
        },
        "/api/CRUDTEMPLATEs/id": {
            "get": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eReads the given CRUDTEMPLATE's account data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "CRUDTEMPLATEs"
                ],
                "summary": "Reads given CRUDTEMPLATE data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the CRUDTEMPLATE to read",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CRUDTEMPLATE.DbReadResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eUpdates given CRUDTEMPLATE with arguments in body",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "CRUDTEMPLATEs"
                ],
                "summary": "Updates given CRUDTEMPLATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the CRUDTEMPLATE to update",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "New arguments to be set in the CRUDTEMPLATE given",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CRUDTEMPLATE.UpdateArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eDeletes the given CRUDTEMPLATE\u003cbr\u003e \u003cb\u003eCareful, there is no turn back or check, once called, this route will delete the CRUDTEMPLATE no matter what\u003c/b\u003e \u003cbr\u003e It also deletes all content related to the CRUDTEMPLATE depending on the parameters of the database",
                "tags": [
                    "CRUDTEMPLATEs"
                ],
                "summary": "Deletes given CRUDTEMPLATE",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the CRUDTEMPLATE to delete",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/account": {
            "get": {
                "description": "\u003cb\u003e⚠️ The user must be logged in ⚠️\u003c/b\u003e\u003cbr\u003e\u003cbr\u003eReads the user's account data\u003cbr\u003e\u003cbr\u003eThe image is a HTTP path to the user's profile picture using the same host:port as the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Reads the user's account data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/account.UserReadResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "\u003cb\u003e⚠️ The user must be logged in ⚠️\u003c/b\u003e\u003cbr\u003e\u003cbr\u003eUpdates the user's account\u003cbr\u003e\u003cbr\u003eThe image must be base64 encoded and must contain the file type in the header (ex: data:image/png;base64,...)\u003cbr\u003e\u003cbr\u003eAll fields are optionals, if a field is empty or not provided, it will not be updated",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Updates the user's account",
                "parameters": [
                    {
                        "description": "New arguments to be set in the user",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/account.UpdateArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.PostLoginResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "\u003cb\u003e⚠️ The user must be logged in ⚠️\u003c/b\u003e\u003cbr\u003e\u003cbr\u003eDeletes the user's account from database, the user will also be logged out\u003cbr\u003e \u003cb\u003eCareful, there is no turn back or check, once called, this route will delete the user no matter what\u003c/b\u003e \u003cbr\u003e It also deletes all content related to the user",
                "tags": [
                    "account"
                ],
                "summary": "Deletes the user's account",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Connection of a user to an existing account\u003cbr\u003eToken will be set in cookies if the arguments combination is valid",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connection of a user to an existing account",
                "parameters": [
                    {
                        "description": "Email + Password combination of the corresponding user",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.Creds"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.PostLoginResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "post": {
                "description": "Disconnection of the user \u003cbr\u003eThe token in the Cookies will be deleted after this route has been called",
                "tags": [
                    "auth"
                ],
                "summary": "Disconnection of the user",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Connection of a new user to a new account\u003cbr\u003eToken will be set in cookies if the username or email is not already taken\u003cbr\u003e\u003cbr\u003eThe image must be base64 encoded and must contain the file type in the header (ex: data:image/png;base64,...)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connection of a new user to a new account",
                "parameters": [
                    {
                        "description": "User related informations that will be later needed for the login process",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/auth.PostLoginResponse"
                        }
                    }
                }
            }
        },
        "/api/characters": {
            "get": {
                "description": "Reads all characters data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Reads all characters data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/characters.RowReadResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/characters/create/firstnode": {
            "get": {
                "description": "Returns the first node of the given ruleset character creation tree",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters creation"
                ],
                "summary": "Returns the first node of the given ruleset",
                "parameters": [
                    {
                        "description": "character related informations that will be later needed for the login process",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/charactersCreate.FirstNodeArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/charactersCreate.RulesetFirstNode"
                        }
                    }
                }
            }
        },
        "/api/characters/create/nextnode": {
            "get": {
                "description": "Returns the next node of the given node depending on the ruleset character creation tree\u003cbr\u003e\u003cbr\u003eThis will check for the tree for all childs of the given node, and return the one(s) that match the condition with the given value\u003cbr\u003e\u003cbr\u003eIf no child matches the condition, it means that the character creation process is finished, and the frontend can send the character creation submission request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters creation"
                ],
                "summary": "Returns the next node",
                "parameters": [
                    {
                        "description": "Actual node id, along with the value and type of the component",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/charactersCreate.NextNodeArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/charactersCreate.NextNodeResponse"
                            }
                        }
                    }
                }
            }
        },
        "/api/characters/create/submit": {
            "post": {
                "description": "Submits a character list of components and creates the character in database\u003cbr\u003e\u003cbr\u003eWill return the id of created character",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters creation"
                ],
                "summary": "Submits a character list of components",
                "parameters": [
                    {
                        "description": "character related informations that will be later needed for the login process",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/charactersCreate.CreateArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/charactersCreate.RulesetFirstNode"
                        }
                    }
                }
            }
        },
        "/api/characters/id": {
            "get": {
                "description": "Reads the given character data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Reads given character data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the character to read",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/characters.RowReadResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eUpdates given character with arguments in body",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "characters"
                ],
                "summary": "Updates given character",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the character to update",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "New arguments to be set in the character given",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/characters.UpdateArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Deletes the given character\u003cbr\u003e \u003cb\u003eCareful, there is no turn back or check, once called, this route will delete the character no matter what\u003c/b\u003e \u003cbr\u003e It also deletes all content related to the character",
                "tags": [
                    "characters"
                ],
                "summary": "Deletes given character",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the character to do the action on",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/dev/callengine": {
            "post": {
                "description": "Makes a HTTP call to whatever URI given using the method, headers and body given in argument, and returns the response of the call",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "Transmit a request via API",
                "parameters": [
                    {
                        "description": "address of the address to call",
                        "name": "address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dev.CallEngineArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dev.Response"
                        }
                    }
                }
            }
        },
        "/api/health": {
            "get": {
                "description": "Healthcheck used (mainly by docker) to check if the api is up and ready to respond",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "apidata"
                ],
                "summary": "Healthcheck for the api",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/rulesets": {
            "get": {
                "description": "Reads all rulesets data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rulesets"
                ],
                "summary": "Reads all rulesets data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/rulesets.DbReadResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a ruleset with arguments in body\u003cbr\u003e\u003cbr\u003eWill return the id of created ruleset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rulesets"
                ],
                "summary": "Creates a ruleset",
                "parameters": [
                    {
                        "description": "ruleset related informations that will be later needed for the login process",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rulesets.CreateRulesetsArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/structs.PostResponse"
                        }
                    }
                }
            }
        },
        "/api/rulesets/id": {
            "get": {
                "description": "Reads the given ruleset's account data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rulesets"
                ],
                "summary": "Reads given ruleset data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the ruleset to read",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rulesets.DbReadResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates given ruleset with arguments in body",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "rulesets"
                ],
                "summary": "Updates given ruleset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the ruleset to update",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "New arguments to be set in the ruleset given",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rulesets.UpdateArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "Deletes the given ruleset\u003cbr\u003e \u003cb\u003eCareful, there is no turn back or check, once called, this route will delete the ruleset no matter what\u003c/b\u003e \u003cbr\u003e It also deletes all content related to the ruleset depending on the parameters of the database",
                "tags": [
                    "rulesets"
                ],
                "summary": "Deletes given ruleset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the ruleset to delete",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eReads all users data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Reads all users data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/users.UserReadResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eCreates a user with arguments in body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Creates a user",
                "parameters": [
                    {
                        "description": "User related informations that will be later needed for the login process",
                        "name": "creds",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.CreateUsersArgs"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/structs.PostResponse"
                        }
                    }
                }
            }
        },
        "/api/users/id": {
            "get": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eReads the given user data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Reads given user data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the user to do the action on",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/users.UserReadResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eUpdates given user with arguments in body",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Updates given user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the user to do the action on",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "New arguments to be set in the user given, along with its id",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.UpdateArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "delete": {
                "description": "⚠️ Only accessible to admins ⚠️\u003cbr\u003e\u003cbr\u003eDeletes the given user\u003cbr\u003e \u003cb\u003eCareful, there is no turn back or check, once called, this route will delete the user no matter what\u003c/b\u003e \u003cbr\u003e It also deletes all content related to the user",
                "tags": [
                    "users"
                ],
                "summary": "Deletes given user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id of the user to do the action on",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/img/:filepath:": {
            "get": {
                "description": "Reads an image file",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "img"
                ],
                "summary": "Reads an image file",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "CRUDTEMPLATE.CreateCRUDTEMPLATEsArgs": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "CRUDTEMPLATE.DbReadResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "CRUDTEMPLATE.UpdateArgs": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "account.UpdateArgs": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "account.UserReadResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "apidata.About": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "auth.Creds": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.PostLoginResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterArgs": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "characters.RowReadResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "player_id": {
                    "type": "string"
                }
            }
        },
        "characters.UpdateArgs": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "player_id": {
                    "type": "string"
                }
            }
        },
        "charactersCreate.CreateArgs": {
            "type": "object",
            "properties": {
                "ruleset_id": {
                    "type": "string"
                }
            }
        },
        "charactersCreate.FirstNodeArgs": {
            "type": "object",
            "properties": {
                "ruleset_id": {
                    "type": "string"
                }
            }
        },
        "charactersCreate.NextNodeArgs": {
            "type": "object",
            "properties": {
                "node_id": {
                    "description": "actual node id",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "charactersCreate.NextNodeResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "charactersCreate.RulesetFirstNode": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dev.CallEngineArgs": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "dev.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "rulesets.CreateRulesetsArgs": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "rulesets.DbReadResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "rulesets.UpdateArgs": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "structs.PostResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "users.CreateUsersArgs": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "users.UpdateArgs": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "users.UserReadResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
