definitions:
  CRUDTEMPLATE.CreateCRUDTEMPLATEsArgs:
    properties:
      name:
        type: string
    type: object
  CRUDTEMPLATE.DbReadResponse:
    properties:
      id:
        type: string
    type: object
  CRUDTEMPLATE.UpdateArgs:
    properties:
      name:
        type: string
    type: object
  account.UpdateArgs:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
  account.UserReadResponse:
    properties:
      email:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  apidata.About:
    properties:
      status:
        type: string
    type: object
  auth.Creds:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  auth.OauthArgs:
    properties:
      code:
        type: string
      service_name:
        type: string
    type: object
  auth.PostLoginResponse:
    properties:
      id:
        type: string
      token:
        type: string
    type: object
  auth.RegisterArgs:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  characters.CreateArgs:
    properties:
      name:
        type: string
      player_id:
        type: string
    type: object
  characters.RowReadResponse:
    properties:
      id:
        type: string
      name:
        type: string
      player_id:
        type: string
    type: object
  characters.UpdateArgs:
    properties:
      name:
        type: string
      player_id:
        type: string
    type: object
  structs.PostResponse:
    properties:
      id:
        type: string
    type: object
  users.CreateUsersArgs:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  users.UpdateArgs:
    properties:
      email:
        type: string
      image:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  users.UserReadResponse:
    properties:
      email:
        type: string
      id:
        type: string
      image:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
info:
  contact: {}
paths:
  /about.json:
    get:
      consumes:
      - application/json
      description: Gives informations about api
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/apidata.About'
      summary: Gives informations about api
      tags:
      - apidata
  /api/CRUDTEMPLATEs:
    get:
      description: ⚠️ Only accessible to admins ⚠️<br><br>Reads all CRUDTEMPLATEs
        data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/CRUDTEMPLATE.DbReadResponse'
            type: array
      summary: Reads all CRUDTEMPLATEs data
      tags:
      - CRUDTEMPLATEs
    post:
      consumes:
      - application/json
      description: ⚠️ Only accessible to admins ⚠️<br><br>Creates a CRUDTEMPLATE with
        arguments in body<br><br>Will return the id of created CRUDTEMPLATE
      parameters:
      - description: CRUDTEMPLATE related informations that will be later needed for
          the login process
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/CRUDTEMPLATE.CreateCRUDTEMPLATEsArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.PostResponse'
      summary: Creates a CRUDTEMPLATE
      tags:
      - CRUDTEMPLATEs
  /api/CRUDTEMPLATEs/id:
    delete:
      description: ⚠️ Only accessible to admins ⚠️<br><br>Deletes the given CRUDTEMPLATE<br>
        <b>Careful, there is no turn back or check, once called, this route will delete
        the CRUDTEMPLATE no matter what</b> <br> It also deletes all content related
        to the CRUDTEMPLATE depending on the parameters of the database
      parameters:
      - description: id of the CRUDTEMPLATE to delete
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Deletes given CRUDTEMPLATE
      tags:
      - CRUDTEMPLATEs
    get:
      description: ⚠️ Only accessible to admins ⚠️<br><br>Reads the given CRUDTEMPLATE's
        account data
      parameters:
      - description: id of the CRUDTEMPLATE to read
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/CRUDTEMPLATE.DbReadResponse'
      summary: Reads given CRUDTEMPLATE data
      tags:
      - CRUDTEMPLATEs
    put:
      consumes:
      - application/json
      description: ⚠️ Only accessible to admins ⚠️<br><br>Updates given CRUDTEMPLATE
        with arguments in body
      parameters:
      - description: id of the CRUDTEMPLATE to update
        in: query
        name: id
        required: true
        type: string
      - description: New arguments to be set in the CRUDTEMPLATE given
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/CRUDTEMPLATE.UpdateArgs'
      responses:
        "200":
          description: OK
      summary: Updates given CRUDTEMPLATE
      tags:
      - CRUDTEMPLATEs
  /api/account:
    delete:
      description: <b>⚠️ The user must be logged in ⚠️</b><br><br>Deletes the user's
        account from database, the user will also be logged out<br> <b>Careful, there
        is no turn back or check, once called, this route will delete the user no
        matter what</b> <br> It also deletes all content related to the user
      responses:
        "200":
          description: OK
      summary: Deletes the user's account
      tags:
      - account
    get:
      description: <b>⚠️ The user must be logged in ⚠️</b><br><br>Reads the user's
        account data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.UserReadResponse'
      summary: Reads the user's account data
      tags:
      - account
    put:
      consumes:
      - application/json
      description: <b>⚠️ The user must be logged in ⚠️</b><br><br>Updates the user's
        account
      parameters:
      - description: New arguments to be set in the user
        in: body
        name: id
        required: true
        schema:
          $ref: '#/definitions/account.UpdateArgs'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.PostLoginResponse'
      summary: Updates the user's account
      tags:
      - account
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Connection of a user to an existing account<br>Token will be set
        in cookies if the arguments combination is valid
      parameters:
      - description: Email + Password combination of the corresponding user
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/auth.Creds'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.PostLoginResponse'
      summary: Connection of a user to an existing account
      tags:
      - auth
  /api/auth/logout:
    post:
      description: Disconnection of the user <br>The token in the Cookies will be
        deleted after this route has been called
      responses:
        "200":
          description: OK
      summary: Disconnection of the user
      tags:
      - auth
  /api/auth/oauth:
    post:
      consumes:
      - application/json
      description: Connection of a user using an OAuth <br>Token will be set in cookies
        if the arguments combination is valid
      parameters:
      - description: Code + Service combination of the corresponding OAuth
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/auth.OauthArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.PostResponse'
      summary: Connection of a user
      tags:
      - auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Connection of a new user to a new account<br>Token will be set
        in cookies if the arguments combination is valid
      parameters:
      - description: User related informations that will be later needed for the login
          process
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.PostLoginResponse'
      summary: Connection of a new user to a new account
      tags:
      - auth
  /api/characters:
    get:
      description: Reads all characters data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/characters.RowReadResponse'
            type: array
      summary: Reads all characters data
      tags:
      - characters
    post:
      consumes:
      - application/json
      description: ⚠️ Only accessible to admins ⚠️<br><br>Creates a character with
        arguments in body<br><br>Will return the id of created character
      parameters:
      - description: character related informations that will be later needed for
          the login process
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/characters.CreateArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.PostResponse'
      summary: Creates a character
      tags:
      - characters
  /api/characters/id:
    delete:
      description: Deletes the given character<br> <b>Careful, there is no turn back
        or check, once called, this route will delete the character no matter what</b>
        <br> It also deletes all content related to the character
      parameters:
      - description: id of the character to do the action on
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Deletes given character
      tags:
      - characters
    get:
      description: Reads the given character data
      parameters:
      - description: id of the character to read
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/characters.RowReadResponse'
      summary: Reads given character data
      tags:
      - characters
    put:
      consumes:
      - application/json
      description: ⚠️ Only accessible to admins ⚠️<br><br>Updates given character
        with arguments in body
      parameters:
      - description: id of the character to update
        in: query
        name: id
        required: true
        type: string
      - description: New arguments to be set in the character given
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/characters.UpdateArgs'
      responses:
        "200":
          description: OK
      summary: Updates given character
      tags:
      - characters
  /api/health:
    get:
      description: Healthcheck used (mainly by docker) to check if the api is up and
        ready to respond
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Healthcheck for the api
      tags:
      - apidata
  /api/users:
    get:
      description: ⚠️ Only accessible to admins ⚠️<br><br>Reads all users data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/users.UserReadResponse'
            type: array
      summary: Reads all users data
      tags:
      - users
    post:
      consumes:
      - application/json
      description: ⚠️ Only accessible to admins ⚠️<br><br>Creates a user with arguments
        in body
      parameters:
      - description: User related informations that will be later needed for the login
          process
        in: body
        name: creds
        required: true
        schema:
          $ref: '#/definitions/users.CreateUsersArgs'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.PostResponse'
      summary: Creates a user
      tags:
      - users
  /api/users/id:
    delete:
      description: ⚠️ Only accessible to admins ⚠️<br><br>Deletes the given user<br>
        <b>Careful, there is no turn back or check, once called, this route will delete
        the user no matter what</b> <br> It also deletes all content related to the
        user
      parameters:
      - description: id of the user to do the action on
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Deletes given user
      tags:
      - users
    get:
      description: ⚠️ Only accessible to admins ⚠️<br><br>Reads the given user data
      parameters:
      - description: id of the user to do the action on
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.UserReadResponse'
      summary: Reads given user data
      tags:
      - users
    put:
      consumes:
      - application/json
      description: ⚠️ Only accessible to admins ⚠️<br><br>Updates given user with
        arguments in body
      parameters:
      - description: id of the user to do the action on
        in: query
        name: id
        required: true
        type: string
      - description: New arguments to be set in the user given, along with its id
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.UpdateArgs'
      responses:
        "200":
          description: OK
      summary: Updates given user
      tags:
      - users
swagger: "2.0"
